import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google"; 
import "./globals.css";

// Configure Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-poppins", // This creates a CSS variable
});

export const metadata: Metadata = {
  title: "Watch Anime Online, Free Anime Streaming Online on GiAnime.to",
  description: "Generated by create next app",
  icons: { icon: "/favicon.webp" },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the variable class to the body */}
      <body className={`${poppins.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
