import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 1. Properly handle Metadata
export const metadata: Metadata = {
  title:
    "Watch Anime Online, Free Anime Streaming Online on GiAnime.to Anime Website",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.webp",
  },
};

// 2. Properly handle Viewport (New in Next.js 14+)
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
